"""Tests for analytical Hessian, vcov(), and score contributions.

Cross-checks the new public APIs (`mltpy.hessian`, `mltpy.score_matrix`,
model methods `vcov`, `estfun`, `score_contributions`, `standard_errors`,
and the updated `_TramModel.summary`) against:

* R references generated by ``reference/generate_reference.R`` — vcov and
  estfun for canonical BoxCox / Colr / Coxph fits.
* Self-consistency identities — ``estfun().sum(axis=0) == -grad(NLL)``
  analytically, and the analytical Hessian against finite differences of
  the analytical gradient across every ``(CensoringType, base_distribution)``
  combination.
"""

from __future__ import annotations

import copy
import pathlib
import re

import numpy as np
import pytest
from scipy.optimize import approx_fprime

from mltpy import (
    MLT,
    CensoredData,
    CensoringType,
    NotFittedError,
    WaldTestResult,
    hessian,
    negative_log_likelihood,
    score_matrix,
)
from mltpy.basis import BernsteinBasis
from mltpy.optimizer import OptimizationResult
from mltpy.tram import BoxCox, Colr, Coxph

REF_DIR = pathlib.Path(__file__).parent.parent / "reference"


# ---------------------------------------------------------------------------
# Self-consistency: estfun.sum == -grad(NLL) across every dispatch path
# ---------------------------------------------------------------------------


def _make_right_censored(n: int, rng: np.random.Generator) -> CensoredData:
    y = np.abs(rng.normal(1.5, 0.5, n)) + 0.1
    event = rng.random(n) > 0.3
    return CensoredData.right_censored(y, censored=~event)


def _make_left_censored(n: int, rng: np.random.Generator) -> CensoredData:
    y = np.abs(rng.normal(1.5, 0.5, n)) + 0.1
    event = rng.random(n) > 0.3
    upper = y
    lower = np.where(event, y, -np.inf)
    exact = np.where(event, y, np.nan)
    return CensoredData(lower=lower, upper=upper, exact=exact)


def _make_interval(n: int, rng: np.random.Generator) -> CensoredData:
    y = np.abs(rng.normal(1.5, 0.5, n)) + 0.1
    half = 0.3
    return CensoredData(lower=y - half, upper=y + half, exact=np.full(n, np.nan))


def _support_from_response(
    y: np.ndarray | CensoredData, pad: float = 0.05
) -> tuple[float, float]:
    """Span every finite observable endpoint of the response.

    Mirrors R ``mlt``'s convention that a ``numeric_var``'s support (and thus
    the ``Bernstein_basis`` it defines) must cover the full range of observed
    events — exact values *and* the finite endpoints of left/right/interval
    censored observations.  The basis is not expected to extrapolate; the
    support is the data support.
    """
    if isinstance(y, CensoredData):
        parts = [
            y.lower[np.isfinite(y.lower)],
            y.upper[np.isfinite(y.upper)],
            y.exact[np.isfinite(y.exact)],
        ]
        vals = np.concatenate([p for p in parts if p.size])
    else:
        vals = np.asarray(y, dtype=float).ravel()
    lo, hi = float(vals.min()), float(vals.max())
    span = hi - lo
    return lo - pad * span, hi + pad * span


_DISTS = ("normal", "logistic", "min_extreme_value", "max_extreme_value")


@pytest.mark.parametrize("base_distribution", _DISTS)
@pytest.mark.parametrize(
    "censoring,builder",
    [
        (CensoringType.NONE, None),
        (CensoringType.RIGHT, _make_right_censored),
        (CensoringType.LEFT, _make_left_censored),
        (CensoringType.INTERVAL, _make_interval),
    ],
)
def test_score_sums_to_minus_nll_gradient(base_distribution, censoring, builder):
    """``score_matrix.sum(0)`` must equal ``-grad(NLL)`` (both are ``grad ℓ``)."""
    rng = np.random.default_rng(123)
    n = 50
    theta = np.concatenate([np.linspace(-1.2, 1.4, 5), [0.25, -0.15]])
    X = rng.normal(0, 1, (n, 2))
    y: np.ndarray | CensoredData
    if builder is None:
        y = np.abs(rng.normal(1.5, 0.5, n)) + 0.1
    else:
        y = builder(n, rng)
    basis = BernsteinBasis(order=4, support=_support_from_response(y))

    _, grad_nll = negative_log_likelihood(
        theta,
        basis,
        y,
        X,
        censoring,
        gradient=True,
        base_distribution=base_distribution,
    )
    scores = score_matrix(
        theta,
        basis,
        y,
        X,
        censoring,
        base_distribution=base_distribution,
    )
    np.testing.assert_allclose(scores.sum(axis=0), -grad_nll, atol=1e-10)


@pytest.mark.parametrize("base_distribution", _DISTS)
@pytest.mark.parametrize(
    "censoring,builder",
    [
        (CensoringType.NONE, None),
        (CensoringType.RIGHT, _make_right_censored),
        (CensoringType.LEFT, _make_left_censored),
        (CensoringType.INTERVAL, _make_interval),
    ],
)
def test_hessian_matches_finite_differences(base_distribution, censoring, builder):
    """Analytical Hessian matches finite differences of the analytical gradient."""
    rng = np.random.default_rng(7)
    n = 40
    theta = np.concatenate([np.linspace(-1.2, 1.4, 5), [0.25, -0.15]])
    X = rng.normal(0, 1, (n, 2))
    if builder is None:
        y: np.ndarray | CensoredData = np.abs(rng.normal(1.5, 0.5, n)) + 0.1
    else:
        y = builder(n, rng)
    basis = BernsteinBasis(order=4, support=_support_from_response(y))

    def grad_fn(t: np.ndarray) -> np.ndarray:
        _, g = negative_log_likelihood(
            t,
            basis,
            y,
            X,
            censoring,
            gradient=True,
            base_distribution=base_distribution,
        )
        return g

    H_ana = hessian(
        theta,
        basis,
        y,
        X,
        censoring,
        base_distribution=base_distribution,
    )
    H_fd = np.stack(
        [
            approx_fprime(theta, lambda t, i=i: grad_fn(t)[i], 1e-5)
            for i in range(len(theta))
        ]
    )
    H_fd = 0.5 * (H_fd + H_fd.T)

    # Symmetry
    np.testing.assert_allclose(H_ana, H_ana.T, atol=1e-10)
    # Match finite differences (step 1e-5 gives ~1e-4 absolute error)
    np.testing.assert_allclose(H_ana, H_fd, atol=5e-3, rtol=1e-3)


# ---------------------------------------------------------------------------
# Fitted-model API: vcov, estfun, score_contributions, standard_errors
# ---------------------------------------------------------------------------


class TestModelVcovAPI:
    def setup_method(self):
        rng = np.random.default_rng(0)
        n = 150
        self.X = rng.normal(0, 1, (n, 2))
        self.y = 0.5 * self.X[:, 0] - 0.3 * self.X[:, 1] + rng.normal(0, 1, n)
        self.m = MLT(
            order=5,
            support=(float(self.y.min() - 0.1), float(self.y.max() + 0.1)),
        ).fit(self.y, X=self.X)

    def test_hessian_shape_and_symmetry(self):
        H = self.m.hessian_
        assert H is not None
        assert H.shape == (self.m.theta_.size, self.m.theta_.size)
        np.testing.assert_allclose(H, H.T, atol=1e-10)

    def test_vcov_is_inverse_of_hessian(self):
        v = self.m.vcov()
        np.testing.assert_allclose(
            v @ self.m.hessian_, np.eye(self.m.theta_.size), atol=1e-8
        )

    def test_standard_errors_positive(self):
        se = self.m.standard_errors()
        assert se.shape == (self.m.theta_.size,)
        assert np.all(se > 0)

    def test_estfun_shape(self):
        ef = self.m.estfun()
        assert ef.shape == (self.m.n_obs_, self.m.theta_.size)

    def test_estfun_cached(self):
        ef1 = self.m.estfun()
        ef2 = self.m.estfun()
        assert ef1 is ef2

    def test_score_contributions_alias(self):
        assert self.m.score_contributions() is self.m.estfun()

    def test_estfun_not_aliased_to_caller_data(self):
        """Mutating y/X after fit() must not change estfun()."""
        rng = np.random.default_rng(9)
        n = 80
        X = rng.normal(0, 1, (n, 2))
        y = 0.5 * X[:, 0] + rng.normal(0, 1, n)
        m = MLT(order=4, support=(float(y.min() - 0.1), float(y.max() + 0.1))).fit(
            y, X=X
        )
        ef_before = m.estfun().copy()
        y[:] = 0.0
        X[:] = 0.0
        np.testing.assert_array_equal(m.estfun(), ef_before)

    def test_estfun_columnsum_is_ml_gradient(self):
        """Column sums = ℓ gradient = -NLL gradient at theta_."""
        _, grad_nll = negative_log_likelihood(
            self.m.theta_,
            self.m.basis,
            self.y,
            self.X,
            CensoringType.NONE,
            gradient=True,
            base_distribution=self.m.base_distribution,
        )
        np.testing.assert_allclose(self.m.estfun().sum(axis=0), -grad_nll, atol=1e-10)


class TestUnfittedGuards:
    def test_unfitted_vcov_raises(self):
        m = MLT(order=3, support=(0.0, 1.0))
        with pytest.raises(NotFittedError):
            m.vcov()

    def test_unfitted_estfun_raises(self):
        m = MLT(order=3, support=(0.0, 1.0))
        with pytest.raises(NotFittedError):
            m.estfun()

    def test_unfitted_standard_errors_raises(self):
        m = MLT(order=3, support=(0.0, 1.0))
        with pytest.raises(NotFittedError):
            m.standard_errors()


class TestNonFiniteRaises:
    """Non-monotone theta gives h'(y) ≤ 0 → the public APIs must raise loudly."""

    def _setup(self):
        rng = np.random.default_rng(1)
        n = 30
        basis = BernsteinBasis(order=4, support=(0.0, 10.0))
        y = np.abs(rng.normal(1.5, 0.5, n)) + 0.1
        X = rng.normal(0, 1, (n, 2))
        # Constant theta_b — h' = 0 everywhere, forcing division by zero.
        theta = np.concatenate([np.full(5, 0.5), [0.25, -0.15]])
        return theta, basis, y, X

    def test_hessian_raises_on_non_monotone_theta(self):
        theta, basis, y, X = self._setup()
        with np.errstate(divide="ignore", invalid="ignore"):
            with pytest.raises(ValueError, match="non-finite"):
                hessian(theta, basis, y, X, CensoringType.NONE)

    def test_score_matrix_raises_on_non_monotone_theta(self):
        theta, basis, y, X = self._setup()
        with np.errstate(divide="ignore", invalid="ignore"):
            with pytest.raises(ValueError, match="non-finite"):
                score_matrix(theta, basis, y, X, CensoringType.NONE)


# ---------------------------------------------------------------------------
# R reference parity
# ---------------------------------------------------------------------------


def _load_vcov_reference(model: str) -> dict:
    """Return dict with y, x, support, theta, vcov, estfun (and event for Coxph)."""
    required = [
        REF_DIR / f"vcov_{model}_y.txt",
        REF_DIR / f"vcov_{model}_x.txt",
        REF_DIR / f"vcov_{model}_support.txt",
        REF_DIR / f"vcov_{model}_theta.txt",
        REF_DIR / f"vcov_{model}_vcov.txt",
        REF_DIR / f"vcov_{model}_estfun.txt",
    ]
    if not all(p.exists() for p in required):
        pytest.skip(
            f"vcov_{model}_* reference files not yet generated — "
            "run Rscript reference/generate_reference.R"
        )
    theta = np.loadtxt(required[3])
    p_plus_q = len(theta)
    vcov_flat = np.loadtxt(required[4])
    estfun_flat = np.loadtxt(required[5])
    n = len(np.loadtxt(required[0]))
    data = {
        "y": np.loadtxt(required[0]),
        "x": np.loadtxt(required[1]).reshape(-1, 1),
        "support": tuple(np.loadtxt(required[2])),
        "theta": theta,
        "vcov": vcov_flat.reshape(p_plus_q, p_plus_q),
        "estfun": estfun_flat.reshape(n, p_plus_q),
    }
    event_path = REF_DIR / f"vcov_{model}_event.txt"
    if event_path.exists():
        data["event"] = np.loadtxt(event_path).astype(int)
    return data


def _assert_hessian_and_scores_match(
    model_cls, base_distribution, censoring, ref: dict, beta_sign: float
):
    """Evaluate mltpy's hessian() and score_matrix() at R's theta and compare.

    mltpy always parametrises the covariate shift as ``h(y|x) = h_b(y) + x'β``.
    tram's convention depends on the model: ``BoxCox`` uses ``negative = TRUE``
    (so ``h = h_b - x'β``) while ``Colr`` and ``Coxph`` use ``negative = FALSE``
    (so ``h = h_b + x'β``, matching mltpy).  ``beta_sign`` is ``-1`` when we
    need to flip the β block (BoxCox) and ``+1`` otherwise.  The sign applies
    to the β entries of theta, the β rows/columns of vcov (via outer product),
    and the β columns of estfun.  ``estfun`` additionally flips overall sign
    because ``sandwich::estfun.mlt`` returns ``∂(-ℓ)/∂θ`` while mltpy's
    ``score_matrix`` returns ``∂ℓ/∂θ``.
    """
    a, b = ref["support"]
    q = ref["x"].shape[1]
    p = len(ref["theta"]) - q
    basis = BernsteinBasis(order=p - 1, support=(float(a), float(b)))
    X = ref["x"]

    sign = np.ones(p + q)
    sign[p:] = beta_sign
    theta_mltpy = ref["theta"] * sign

    if "event" in ref:
        cd = CensoredData.right_censored(ref["y"], censored=ref["event"] == 0)
        y_obj: np.ndarray | CensoredData = cd
    else:
        y_obj = ref["y"]

    H = hessian(
        theta_mltpy, basis, y_obj, X, censoring, base_distribution=base_distribution
    )
    vcov_mltpy = np.linalg.inv(H)
    vcov_ref_mltpy_conv = ref["vcov"] * np.outer(sign, sign)
    np.testing.assert_allclose(vcov_mltpy, vcov_ref_mltpy_conv, rtol=1e-4, atol=1e-6)

    scores_mltpy = score_matrix(
        theta_mltpy, basis, y_obj, X, censoring, base_distribution=base_distribution
    )
    scores_ref_mltpy_conv = -ref["estfun"] * sign[None, :]
    np.testing.assert_allclose(
        scores_mltpy, scores_ref_mltpy_conv, rtol=1e-5, atol=1e-8
    )


def test_boxcox_vcov_estfun_against_R():
    ref = _load_vcov_reference("boxcox")
    _assert_hessian_and_scores_match(
        BoxCox, "normal", CensoringType.NONE, ref, beta_sign=-1.0
    )


def test_colr_vcov_estfun_against_R():
    ref = _load_vcov_reference("colr")
    _assert_hessian_and_scores_match(
        Colr, "logistic", CensoringType.NONE, ref, beta_sign=+1.0
    )


def test_coxph_vcov_estfun_against_R():
    ref = _load_vcov_reference("coxph")
    _assert_hessian_and_scores_match(
        Coxph, "min_extreme_value", CensoringType.RIGHT, ref, beta_sign=+1.0
    )


# ---------------------------------------------------------------------------
# Summary formatting
# ---------------------------------------------------------------------------


class TestSummaryCoefTable:
    def test_coef_table_present_with_covariates(self):
        rng = np.random.default_rng(0)
        n = 150
        X = rng.normal(0, 1, (n, 2))
        y = 0.5 * X[:, 0] - 0.3 * X[:, 1] + rng.normal(0, 1, n)
        m = BoxCox(support=(float(y.min() - 0.1), float(y.max() + 0.1)), order=5).fit(
            y, X=X
        )
        summary = m.summary()
        assert "Coefficients:" in summary
        assert "Estimate" in summary
        assert "Std. Error" in summary
        assert "z value" in summary
        assert "Pr(>|z|)" in summary
        # Two covariate rows, named X1 and X2 by default
        assert re.search(r"\bX1\b", summary)
        assert re.search(r"\bX2\b", summary)

    def test_coef_table_absent_without_covariates(self):
        rng = np.random.default_rng(1)
        y = rng.normal(0, 1, 200)
        m = BoxCox(support=(float(y.min() - 0.1), float(y.max() + 0.1)), order=4).fit(y)
        summary = m.summary()
        assert "Coefficients:" not in summary


# ---------------------------------------------------------------------------
# Sandwich variance–covariance matrix
# ---------------------------------------------------------------------------


class TestSandwichVcov:
    def setup_method(self):
        rng = np.random.default_rng(42)
        n = 200
        self.X = rng.normal(0, 1, (n, 2))
        self.y = 0.5 * self.X[:, 0] - 0.3 * self.X[:, 1] + rng.normal(0, 1, n)
        self.m = MLT(
            order=5,
            support=(float(self.y.min() - 0.1), float(self.y.max() + 0.1)),
        ).fit(self.y, X=self.X)

    def test_sandwich_vcov_shape(self):
        V = self.m.sandwich_vcov()
        k = self.m.theta_.size
        assert V.shape == (k, k)

    def test_sandwich_vcov_symmetric(self):
        V = self.m.sandwich_vcov()
        np.testing.assert_allclose(V, V.T, atol=1e-12)

    def test_sandwich_vcov_positive_diagonal(self):
        V = self.m.sandwich_vcov()
        assert np.all(np.diag(V) > 0)

    def test_sandwich_vcov_formula(self):
        """V_sandwich = H^{-1} M H^{-1} where M = estfun().T @ estfun()."""
        V = self.m.sandwich_vcov()
        H = self.m.hessian_
        H_inv = np.linalg.inv(H)
        ef = self.m.estfun()
        M = ef.T @ ef
        V_expected = H_inv @ M @ H_inv
        np.testing.assert_allclose(V, V_expected, atol=1e-12)

    def test_sandwich_vcov_unfitted_raises(self):
        m = MLT(order=3, support=(0.0, 1.0))
        with pytest.raises(NotFittedError):
            m.sandwich_vcov()

    def test_sandwich_se_positive(self):
        se = self.m.sandwich_se()
        assert se.shape == (self.m.theta_.size,)
        assert np.all(se > 0)

    def test_sandwich_se_unfitted_raises(self):
        m = MLT(order=3, support=(0.0, 1.0))
        with pytest.raises(NotFittedError):
            m.sandwich_se()


# ---------------------------------------------------------------------------
# sandwich_vcov(regularize=...) and sandwich_se(regularize=...)
# ---------------------------------------------------------------------------


class TestSandwichVcovRegularize:
    """sandwich_vcov / sandwich_se inherit the vcov bread regularization (#83)."""

    def setup_method(self):
        rng = np.random.default_rng(42)
        n = 200
        self.X = rng.normal(0, 1, (n, 2))
        self.y = 0.5 * self.X[:, 0] - 0.3 * self.X[:, 1] + rng.normal(0, 1, n)
        self.m = MLT(
            order=5,
            support=(float(self.y.min() - 0.1), float(self.y.max() + 0.1)),
        ).fit(self.y, X=self.X)

    def _make_singular_constrained_model(self):
        """Copy of self.m with an injected singular Hessian and active-constraint
        metadata (same helper pattern as TestVcovRegularize)."""
        m = copy.copy(self.m)
        p = m.theta_.size

        H = self.m.hessian_.copy()
        H[0, :] = 0.0
        H[:, 0] = 0.0
        m.hessian_ = H

        order = p - 2
        A = np.zeros((order, p))
        for i in range(order):
            A[i, i + 1] = 1.0
            A[i, i] = -1.0
        m._A_ineq_ = A

        mu = np.zeros(order)
        mu[0] = 5.0
        rho = 100.0
        m.result_ = OptimizationResult(
            theta=m.theta_,
            log_likelihood=float(m.result_.log_likelihood),
            converged=True,
            n_iter=m.result_.n_iter,
            n_restarts=m.result_.n_restarts,
            solver_message=m.result_.solver_message,
            rho_final=rho,
            mu_ineq=mu,
        )
        return m

    def test_sandwich_vcov_accepts_regularize_kwarg(self):
        """sandwich_vcov(regularize='active') and sandwich_vcov(regularize=None) callable."""
        _ = self.m.sandwich_vcov(regularize="active")
        _ = self.m.sandwich_vcov(regularize=None)

    def test_sandwich_vcov_default_is_active(self):
        """sandwich_vcov() == sandwich_vcov(regularize='active') on a well-conditioned fit."""
        V_default = self.m.sandwich_vcov()
        V_active = self.m.sandwich_vcov(regularize="active")
        np.testing.assert_array_equal(V_default, V_active)

    def test_sandwich_vcov_bread_is_vcov(self):
        """V_sandwich = vcov() @ meat @ vcov() — bread computed via vcov()."""
        V = self.m.sandwich_vcov(regularize="active")
        bread = self.m.vcov(regularize="active")
        meat = self.m.estfun().T @ self.m.estfun()
        V_expected = bread @ meat @ bread
        np.testing.assert_allclose(V, V_expected, atol=1e-12)

    def test_sandwich_vcov_invalid_regularize_raises(self):
        with pytest.raises(ValueError, match="regularize"):
            self.m.sandwich_vcov(regularize="unknown")

    def test_sandwich_vcov_active_finite_on_singular_constrained(self):
        """regularize='active' recovers finite sandwich on singular Hessian."""
        m = self._make_singular_constrained_model()
        V = m.sandwich_vcov(regularize="active")
        assert np.all(np.isfinite(V))
        assert V.shape == (m.theta_.size, m.theta_.size)

    def test_sandwich_vcov_none_raises_on_singular(self):
        """regularize=None propagates RuntimeError from vcov on singular Hessian."""
        m = self._make_singular_constrained_model()
        with pytest.raises(RuntimeError, match="singular"):
            m.sandwich_vcov(regularize=None)

    def test_sandwich_se_accepts_regularize_kwarg(self):
        se = self.m.sandwich_se(regularize="active")
        assert se.shape == (self.m.theta_.size,)
        assert np.all(se > 0)

    def test_sandwich_se_default_is_active(self):
        se_default = self.m.sandwich_se()
        se_active = self.m.sandwich_se(regularize="active")
        np.testing.assert_array_equal(se_default, se_active)


# ---------------------------------------------------------------------------
# Wald tests
# ---------------------------------------------------------------------------


class TestWaldTest:
    def setup_method(self):
        rng = np.random.default_rng(99)
        n = 300
        self.X = rng.normal(0, 1, (n, 2))
        self.y = 0.7 * self.X[:, 0] - 0.4 * self.X[:, 1] + rng.normal(0, 1, n)
        self.m = MLT(
            order=5,
            support=(float(self.y.min() - 0.1), float(self.y.max() + 0.1)),
        ).fit(self.y, X=self.X)
        # Bernstein + 2 covariate params
        self.p = self.m.theta_.size

    def test_wald_test_returns_WaldTestResult(self):
        R = np.eye(1, self.p, self.p - 1)  # test last param = 0
        result = self.m.wald_test(R)
        assert isinstance(result, WaldTestResult)

    def test_wald_test_fields(self):
        R = np.eye(1, self.p, self.p - 1)
        result = self.m.wald_test(R)
        assert result.statistic >= 0
        assert result.df == 1
        assert 0.0 <= result.p_value <= 1.0

    def test_wald_test_two_constraints(self):
        # Test both covariate params jointly = 0
        R = np.zeros((2, self.p))
        R[0, -2] = 1.0
        R[1, -1] = 1.0
        result = self.m.wald_test(R)
        assert result.df == 2
        # Both should be non-zero (generated with non-zero beta), so should reject
        assert result.p_value < 0.05

    def test_wald_test_with_r_vector(self):
        """H0: theta[last] = r should match H0: theta[last] - r = 0."""
        k = self.p
        R = np.eye(1, k, k - 1)
        r_val = self.m.theta_[-1]  # test at the MLE value → statistic near 0
        result_at_mle = self.m.wald_test(R, r=np.array([r_val]))
        assert result_at_mle.statistic < 0.01  # near 0 at MLE

    def test_wald_test_statistic_formula(self):
        """W = (Rθ - r)^T [R V R^T]^{-1} (Rθ - r) / df."""
        R = np.zeros((2, self.p))
        R[0, -2] = 1.0
        R[1, -1] = 1.0
        r = np.zeros(2)
        result = self.m.wald_test(R, r=r)
        V = self.m.vcov()
        diff = R @ self.m.theta_ - r
        RVR = R @ V @ R.T
        W_expected = float(diff @ np.linalg.inv(RVR) @ diff)
        np.testing.assert_allclose(result.statistic, W_expected, rtol=1e-10)

    def test_wald_test_sandwich_uses_sandwich_vcov(self):
        """With vcov='sandwich' the test uses sandwich_vcov()."""
        R = np.zeros((2, self.p))
        R[0, -2] = 1.0
        R[1, -1] = 1.0
        r = np.zeros(2)
        result_sandwich = self.m.wald_test(R, r=r, vcov="sandwich")
        # Statistic differs when sandwich != information vcov
        V_sand = self.m.sandwich_vcov()
        diff = R @ self.m.theta_ - r
        RVR = R @ V_sand @ R.T
        W_sandwich = float(diff @ np.linalg.inv(RVR) @ diff)
        np.testing.assert_allclose(result_sandwich.statistic, W_sandwich, rtol=1e-10)

    def test_wald_test_unfitted_raises(self):
        m = MLT(order=3, support=(0.0, 1.0))
        R = np.eye(1, 4, 3)
        with pytest.raises(NotFittedError):
            m.wald_test(R)

    def test_wald_test_invalid_R_shape_raises(self):
        # R must have self.p columns
        R = np.eye(2, self.p + 1)
        with pytest.raises(ValueError, match="columns"):
            self.m.wald_test(R)

    def test_wald_test_repr(self):
        R = np.eye(1, self.p, self.p - 1)
        result = self.m.wald_test(R)
        s = repr(result)
        assert "Wald" in s
        assert "statistic" in s or "W" in s


# ---------------------------------------------------------------------------
# vcov(regularize=...) and standard_errors(regularize=...)
# ---------------------------------------------------------------------------


class TestVcovRegularize:
    """Tests for vcov(regularize='active') and standard_errors(regularize=...).

    Fixtures
    --------
    self.m  — a well-identified MLT fit with no active constraints.
    """

    def setup_method(self):
        rng = np.random.default_rng(42)
        n = 200
        self.X = rng.normal(0, 1, (n, 2))
        self.y = 0.5 * self.X[:, 0] - 0.3 * self.X[:, 1] + rng.normal(0, 1, n)
        self.m = MLT(
            order=5,
            support=(float(self.y.min() - 0.1), float(self.y.max() + 0.1)),
        ).fit(self.y, X=self.X)

    def test_vcov_accepts_regularize_kwarg(self):
        """vcov(regularize='active') and vcov(regularize=None) are callable."""
        _ = self.m.vcov(regularize="active")
        _ = self.m.vcov(regularize=None)

    def test_vcov_active_matches_plain_on_invertible_hessian(self):
        """No active constraints → regularize='active' gives the same matrix."""
        v_active = self.m.vcov(regularize="active")
        v_none = self.m.vcov(regularize=None)
        np.testing.assert_allclose(v_active, v_none, rtol=1e-12, atol=0)

    def test_standard_errors_accepts_regularize_kwarg(self):
        se = self.m.standard_errors(regularize="active")
        assert se.shape == (self.m.theta_.size,)
        assert np.all(se > 0)

    def test_standard_errors_default_uses_active(self):
        """standard_errors() == standard_errors(regularize='active')."""
        se_default = self.m.standard_errors()
        se_active = self.m.standard_errors(regularize="active")
        np.testing.assert_array_equal(se_default, se_active)

    def test_vcov_none_raises_on_singular_hessian(self):
        """regularize=None preserves old RuntimeError on singular Hessian."""
        m = copy.copy(self.m)
        # Inject a rank-deficient Hessian (last row/col zeroed out).
        H = self.m.hessian_.copy()
        H[-1, :] = 0.0
        H[:, -1] = 0.0
        m.hessian_ = H
        with pytest.raises(RuntimeError, match="singular"):
            m.vcov(regularize=None)

    def _make_singular_constrained_model(self):
        """Return a copy of self.m whose Hessian is singular and which has
        active-constraint metadata injected (simulating an auglag fit where
        the last Bernstein increment is exactly zero)."""
        m = copy.copy(self.m)
        p = m.theta_.size

        # Make Hessian singular: zero out the first row/col (corresponds to
        # the first Bernstein coefficient being on its monotonicity boundary).
        H = self.m.hessian_.copy()
        H[0, :] = 0.0
        H[:, 0] = 0.0
        m.hessian_ = H

        # Constraint matrix: forward-difference operator on the first p-2
        # Bernstein params (mimicking build_constraints output).
        order = p - 2  # 2 covariate params in self.m
        A = np.zeros((order, p))
        for i in range(order):
            A[i, i + 1] = 1.0
            A[i, i] = -1.0
        m._A_ineq_ = A

        # Inject a realistic OptimizationResult with active multipliers.
        # First constraint (i=0) is active → mu_ineq[0] > 0.
        mu = np.zeros(order)
        mu[0] = 5.0  # active
        rho = 100.0
        m.result_ = OptimizationResult(
            theta=m.theta_,
            log_likelihood=float(m.result_.log_likelihood),
            converged=True,
            n_iter=m.result_.n_iter,
            n_restarts=m.result_.n_restarts,
            solver_message=m.result_.solver_message,
            rho_final=rho,
            mu_ineq=mu,
        )
        return m

    def test_vcov_active_returns_finite_on_singular_with_constraint_data(self):
        """regularize='active' recovers from singular H via penalty augmentation."""
        m = self._make_singular_constrained_model()
        v = m.vcov(regularize="active")
        assert np.all(np.isfinite(v))
        assert v.shape == (m.theta_.size, m.theta_.size)
        # Diagonal must be non-negative for a valid covariance matrix.
        assert np.all(np.diag(v) >= 0)

    def test_standard_errors_active_finite_on_constrained_model(self):
        """standard_errors() (default) does not raise on singular-H model."""
        m = self._make_singular_constrained_model()
        se = m.standard_errors()
        assert np.all(np.isfinite(se))
        assert se.shape == (m.theta_.size,)
        assert np.all(se >= 0)

    def test_vcov_invalid_regularize_raises_valueerror(self):
        with pytest.raises(ValueError, match="regularize"):
            self.m.vcov(regularize="unknown")


# ---------------------------------------------------------------------------
# vcov(regularize='auglag') — unconditional active-set augmentation
# ---------------------------------------------------------------------------


class TestVcovAuglag:
    """``regularize='auglag'`` always applies the active-set penalty.

    Distinct from ``'active'`` (which only augments on bare-inversion
    failure) and from ``None`` (no augmentation, raise on singular).  The
    motivating case is scaled-baseline Coxph, where R's
    ``vcov(as.mlt(fit))`` applies the augmentation but mltpy's bare
    ``inv(H)`` doesn't — see ``test_scaling_inference.py`` for the parity
    check.  These tests pin the mode's algebraic identity and its
    relationship to the other two modes on plain (unscaled) fits.
    """

    def setup_method(self):
        rng = np.random.default_rng(0)
        n = 150
        self.X = rng.normal(0, 1, (n, 2))
        self.y = 0.5 * self.X[:, 0] - 0.3 * self.X[:, 1] + rng.normal(0, 1, n)
        self.m = MLT(
            order=5,
            support=(float(self.y.min() - 0.1), float(self.y.max() + 0.1)),
        ).fit(self.y, X=self.X)

        # A second fit that lands at an *interior* MLE (no monotonicity
        # constraint active).  The seed-0 fixture above always binds one
        # increment, so it can only exercise the active-set branch; this one
        # exercises the empty-active-set branch, where 'auglag' must collapse
        # to bare inv(H).  (seed 1 / order 5 → 0 of 5 constraints active.)
        rng_i = np.random.default_rng(1)
        Xi = rng_i.normal(0, 1, (200, 2))
        yi = 0.5 * Xi[:, 0] - 0.3 * Xi[:, 1] + rng_i.normal(0, 1, 200)
        self.m_interior = MLT(
            order=5,
            support=(float(yi.min() - 0.1), float(yi.max() + 0.1)),
        ).fit(yi, X=Xi)

    def test_vcov_auglag_callable(self):
        """``vcov(regularize='auglag')`` returns a finite symmetric matrix."""
        V = self.m.vcov(regularize="auglag")
        k = self.m.theta_.size
        assert V.shape == (k, k)
        np.testing.assert_allclose(V, V.T, atol=1e-10)
        assert np.all(np.isfinite(V))

    def test_vcov_auglag_equals_constrained_covariance(self):
        """``vcov('auglag')`` equals the active-set-constrained covariance.

        Defining property of the mode.  The constrained covariance is the
        ρ→∞ limit of the old penalty form ``(H + ρ·Aᵀ_active·A_active)⁻¹``;
        for an invertible ``H`` it has the closed form
        ``H⁻¹ − H⁻¹Aᵀ(AH⁻¹Aᵀ)⁻¹AH⁻¹`` (the standard projection).  Compared
        element-wise against that hand-rolled projection — the two paths must
        agree exactly.  This is *independent* of the optimiser's final
        penalty ``rho_final`` (the previous implementation's ρ-dependence was
        a latent bug, masked only because the augmented Lagrangian used to
        inflate ρ to ~1e8; see ``test_scaling_inference.py`` for the R-parity
        check that this restores).
        """
        V = self.m.vcov(regularize="auglag")
        assert self.m._A_ineq_ is not None and self.m.result_ is not None
        assert self.m.result_.mu_ineq is not None
        active = self.m.result_.mu_ineq > self.m._ACTIVE_CONSTRAINT_TOL
        H = self.m.hessian_
        if active.any():
            A_act = self.m._A_ineq_[active, :]
            H_inv = np.linalg.inv(H)
            M = A_act @ H_inv @ A_act.T
            V_expected = H_inv - H_inv @ A_act.T @ np.linalg.solve(M, A_act @ H_inv)
        else:
            V_expected = np.linalg.inv(H)
        np.testing.assert_allclose(V, V_expected, atol=1e-10)

    def test_vcov_auglag_diverges_from_active_when_constraint_binds(self):
        """When a constraint binds, ``'auglag' != 'active'``.

        ``'active'`` only augments on bare-inversion failure, so on an
        invertible ``H`` it equals ``vcov(None)``.  ``'auglag'`` augments
        unconditionally.  This test pins the divergence when there is
        something to augment, and the equivalence to ``'active'`` when
        there is nothing (so a regression that silently turns
        ``'auglag'`` into a no-op would be caught).
        """
        v_auglag = self.m.vcov(regularize="auglag")
        v_active = self.m.vcov(regularize="active")
        mu = self.m.result_.mu_ineq if self.m.result_ is not None else None
        any_active = mu is not None and bool((mu > self.m._ACTIVE_CONSTRAINT_TOL).any())
        if any_active:
            assert not np.allclose(v_auglag, v_active, rtol=1e-8, atol=1e-10)
        else:
            np.testing.assert_allclose(v_auglag, v_active, rtol=1e-12, atol=0)

    def test_vcov_auglag_matches_bare_when_no_constraint_binds(self):
        """With an empty active set, ``vcov('auglag') == vcov(None)``.

        ``'auglag'`` augments unconditionally using the *active* constraint
        set; when no row of ``A_ineq`` binds the penalty is zero, so the
        augmented Hessian equals ``H`` and the inverse is bare.  This pins
        that the augmentation collapses to a no-op on an interior MLE — a
        regression that augmented spuriously (or mis-detected the active set)
        would be caught here.  Uses ``self.m_interior`` because the seed-0
        ``self.m`` always binds a constraint.
        """
        m = self.m_interior
        assert m.result_ is not None and m.result_.mu_ineq is not None
        # Guard the premise: this fixture must genuinely have no active row.
        assert not (m.result_.mu_ineq > m._ACTIVE_CONSTRAINT_TOL).any()
        v_auglag = m.vcov(regularize="auglag")
        v_none = m.vcov(regularize=None)
        np.testing.assert_allclose(v_auglag, v_none, rtol=1e-12, atol=0)

    def test_vcov_invalid_regularize_message_lists_auglag(self):
        """The error message mentions all three legal values."""
        with pytest.raises(ValueError, match=r"'active'.*'auglag'"):
            self.m.vcov(regularize="unknown")

    def test_sandwich_vcov_auglag_forwards_to_vcov(self):
        """``sandwich_vcov(regularize='auglag')`` uses augmented bread."""
        V = self.m.sandwich_vcov(regularize="auglag")
        bread = self.m.vcov(regularize="auglag")
        ef = self.m.estfun()
        expected = bread @ (ef.T @ ef) @ bread
        np.testing.assert_allclose(V, expected, atol=1e-12)

    def test_wald_test_auglag_forwards_to_vcov(self):
        """``wald_test(R, regularize='auglag')`` uses augmented vcov."""
        k = self.m.theta_.size
        R = np.zeros((1, k))
        R[0, -1] = 1.0
        result = self.m.wald_test(R, regularize="auglag")
        V = self.m.vcov(regularize="auglag")
        diff = R @ self.m.theta_
        RVR = R @ V @ R.T
        W_expected = float(diff @ np.linalg.inv(RVR) @ diff)
        np.testing.assert_allclose(result.statistic, W_expected, rtol=1e-10)


# ---------------------------------------------------------------------------
# wald_test(regularize=...) — #84
# ---------------------------------------------------------------------------


class TestWaldTestRegularize:
    """wald_test forwards regularize to vcov / sandwich_vcov (#84)."""

    def setup_method(self):
        rng = np.random.default_rng(42)
        n = 200
        self.X = rng.normal(0, 1, (n, 2))
        self.y = 0.5 * self.X[:, 0] - 0.3 * self.X[:, 1] + rng.normal(0, 1, n)
        self.m = MLT(
            order=5,
            support=(float(self.y.min() - 0.1), float(self.y.max() + 0.1)),
        ).fit(self.y, X=self.X)
        p = self.m.theta_.size
        # Test last covariate parameter = 0.
        self.R = np.eye(1, p, p - 1)

    def _make_singular_constrained_model(self):
        m = copy.copy(self.m)
        p = m.theta_.size

        H = self.m.hessian_.copy()
        H[0, :] = 0.0
        H[:, 0] = 0.0
        m.hessian_ = H

        order = p - 2
        A = np.zeros((order, p))
        for i in range(order):
            A[i, i + 1] = 1.0
            A[i, i] = -1.0
        m._A_ineq_ = A

        mu = np.zeros(order)
        mu[0] = 5.0
        rho = 100.0
        m.result_ = OptimizationResult(
            theta=m.theta_,
            log_likelihood=float(m.result_.log_likelihood),
            converged=True,
            n_iter=m.result_.n_iter,
            n_restarts=m.result_.n_restarts,
            solver_message=m.result_.solver_message,
            rho_final=rho,
            mu_ineq=mu,
        )
        return m

    def test_wald_test_accepts_regularize_kwarg(self):
        """wald_test(R, regularize='active') and regularize=None are callable."""
        _ = self.m.wald_test(self.R, regularize="active")
        _ = self.m.wald_test(self.R, regularize=None)

    def test_wald_test_default_regularize_is_active(self):
        """wald_test(R) == wald_test(R, regularize='active')."""
        res_default = self.m.wald_test(self.R)
        res_active = self.m.wald_test(self.R, regularize="active")
        assert res_default.statistic == res_active.statistic

    def test_wald_test_information_forwards_regularize(self):
        """wald_test(R, regularize=...) passes regularize to vcov() on information path."""
        res = self.m.wald_test(self.R, regularize="active")
        V = self.m.vcov(regularize="active")
        diff = self.R @ self.m.theta_
        RVR = self.R @ V @ self.R.T
        W_expected = float(diff @ np.linalg.inv(RVR) @ diff)
        np.testing.assert_allclose(res.statistic, W_expected, rtol=1e-10)

    def test_wald_test_sandwich_forwards_regularize(self):
        """wald_test(R, vcov='sandwich', regularize=...) passes regularize to sandwich_vcov()."""
        res = self.m.wald_test(self.R, vcov="sandwich", regularize="active")
        V = self.m.sandwich_vcov(regularize="active")
        diff = self.R @ self.m.theta_
        RVR = self.R @ V @ self.R.T
        W_expected = float(diff @ np.linalg.inv(RVR) @ diff)
        np.testing.assert_allclose(res.statistic, W_expected, rtol=1e-10)

    def test_wald_test_active_finite_on_singular_constrained(self):
        """regularize='active' gives a finite Wald statistic on a singular Hessian fit."""
        m = self._make_singular_constrained_model()
        res = m.wald_test(self.R, regularize="active")
        assert np.isfinite(res.statistic)
        assert 0.0 <= res.p_value <= 1.0

    def test_wald_test_none_raises_on_singular(self):
        """regularize=None propagates RuntimeError from vcov on singular Hessian."""
        m = self._make_singular_constrained_model()
        with pytest.raises(RuntimeError, match="singular"):
            m.wald_test(self.R, regularize=None)
