"""R-parity test for pymlt's auglag solver.

Loads the reference data generated by
``tests/r_scripts/generate_auglag_reference.R`` (alabama::auglag) and
asserts that pymlt's auglag solver produces the same theta and log-likelihood
to within rtol=1e-6, atol=1e-10.

The reference file is committed to the repository so the test can run in CI
without R installed.  To regenerate it run::

    Rscript tests/r_scripts/generate_auglag_reference.R
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np
import pytest

_REF_PATH = (
    Path(__file__).resolve().parent / "reference_data" / "auglag" / "lm_n50_seed42.json"
)


@pytest.fixture(scope="module")
def reference() -> dict:
    """Load the alabama::auglag reference JSON."""
    if not _REF_PATH.is_file():
        pytest.skip(f"Reference file not found: {_REF_PATH}")
    with _REF_PATH.open() as fh:
        return json.load(fh)


def test_auglag_theta_matches_r(reference: dict) -> None:
    """pymlt auglag theta must match alabama::auglag theta within rtol=1e-6."""
    from pymlt.basis import BernsteinBasis
    from pymlt.optimizer import OptimizerConfig, optimize

    y = np.array(reference["y"], dtype=np.float64)
    support = tuple(float(v) for v in reference["support"])
    theta_r = np.array(reference["theta"], dtype=np.float64)

    basis = BernsteinBasis(order=reference["order"], support=support)
    config = OptimizerConfig(solver="auglag")
    result = optimize(basis, y, config=config)

    np.testing.assert_allclose(
        result.theta,
        theta_r,
        rtol=1e-6,
        atol=1e-10,
        err_msg=(
            f"pymlt theta {result.theta} differs from R reference {theta_r} "
            f"beyond tolerance"
        ),
    )


def test_auglag_loglik_matches_r(reference: dict) -> None:
    """pymlt auglag log-likelihood must match alabama::auglag within rtol=1e-6."""
    from pymlt.basis import BernsteinBasis
    from pymlt.optimizer import OptimizerConfig, optimize

    y = np.array(reference["y"], dtype=np.float64)
    support = tuple(float(v) for v in reference["support"])
    ll_r = float(reference["log_likelihood"])

    basis = BernsteinBasis(order=reference["order"], support=support)
    config = OptimizerConfig(solver="auglag")
    result = optimize(basis, y, config=config)

    np.testing.assert_allclose(
        result.log_likelihood,
        ll_r,
        rtol=1e-6,
        atol=1e-10,
        err_msg=(
            f"pymlt log-likelihood {result.log_likelihood:.10f} differs from "
            f"R reference {ll_r:.10f} beyond tolerance"
        ),
    )


def test_auglag_converged(reference: dict) -> None:
    """The auglag solver must report convergence on the reference fixture."""
    from pymlt.basis import BernsteinBasis
    from pymlt.optimizer import OptimizerConfig, optimize

    y = np.array(reference["y"], dtype=np.float64)
    support = tuple(float(v) for v in reference["support"])

    basis = BernsteinBasis(order=reference["order"], support=support)
    config = OptimizerConfig(solver="auglag")
    result = optimize(basis, y, config=config)

    assert result.converged, (
        f"auglag did not converge on reference fixture; "
        f"kkt_residual={result.kkt_residual:.3e}, message={result.solver_message!r}"
    )


def test_auglag_monotonicity_satisfied(reference: dict) -> None:
    """Bernstein coefficients must be non-decreasing at the auglag optimum."""
    from pymlt.basis import BernsteinBasis
    from pymlt.optimizer import OptimizerConfig, optimize

    y = np.array(reference["y"], dtype=np.float64)
    support = tuple(float(v) for v in reference["support"])
    order = int(reference["order"])

    basis = BernsteinBasis(order=order, support=support)
    config = OptimizerConfig(solver="auglag")
    result = optimize(basis, y, config=config)

    theta_b = result.theta[: order + 1]
    assert np.all(np.diff(theta_b) >= -1e-6), (
        f"Monotonicity violated at auglag optimum: theta_b={theta_b}"
    )


def test_reference_starting_point(reference: dict) -> None:
    """Sanity check: stored starting point matches pymlt's _initial_theta."""
    from pymlt.optimizer import _initial_theta

    order = int(reference["order"])
    stored_start = np.array(reference["starting_point"], dtype=np.float64)
    expected_start = _initial_theta(order + 1, None)
    np.testing.assert_allclose(stored_start, expected_start, atol=1e-15)
