"""R-parity test for pymlt's auglag solver.

Loads the reference data generated by
``tests/r_scripts/generate_auglag_reference.R`` (alabama::auglag) and
asserts that pymlt's auglag solver produces the same theta and log-likelihood
to within rtol=1e-6, atol=1e-10.

The reference file is committed to the repository so the test can run in CI
without R installed.  To regenerate it run::

    Rscript tests/r_scripts/generate_auglag_reference.R
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np
import pytest

_REF_PATH = (
    Path(__file__).resolve().parent / "reference_data" / "auglag" / "lm_n50_seed42.json"
)


@pytest.fixture(scope="module")
def reference() -> dict:
    """Load the alabama::auglag reference JSON."""
    if not _REF_PATH.is_file():
        pytest.skip(f"Reference file not found: {_REF_PATH}")
    with _REF_PATH.open() as fh:
        return json.load(fh)


def test_auglag_theta_matches_r(reference: dict) -> None:
    """pymlt auglag theta must match alabama::auglag theta within rtol=1e-6."""
    from pymlt.basis import BernsteinBasis
    from pymlt.optimizer import OptimizerConfig, optimize

    y = np.array(reference["y"], dtype=np.float64)
    support = tuple(float(v) for v in reference["support"])
    theta_r = np.array(reference["theta"], dtype=np.float64)

    basis = BernsteinBasis(order=reference["order"], support=support)
    config = OptimizerConfig(solver="auglag")
    result = optimize(basis, y, config=config)

    np.testing.assert_allclose(
        result.theta,
        theta_r,
        rtol=1e-6,
        atol=1e-10,
        err_msg=(
            f"pymlt theta {result.theta} differs from R reference {theta_r} "
            f"beyond tolerance"
        ),
    )


def test_auglag_loglik_matches_r(reference: dict) -> None:
    """pymlt auglag log-likelihood must match alabama::auglag within rtol=1e-6."""
    from pymlt.basis import BernsteinBasis
    from pymlt.optimizer import OptimizerConfig, optimize

    y = np.array(reference["y"], dtype=np.float64)
    support = tuple(float(v) for v in reference["support"])
    ll_r = float(reference["log_likelihood"])

    basis = BernsteinBasis(order=reference["order"], support=support)
    config = OptimizerConfig(solver="auglag")
    result = optimize(basis, y, config=config)

    np.testing.assert_allclose(
        result.log_likelihood,
        ll_r,
        rtol=1e-6,
        atol=1e-10,
        err_msg=(
            f"pymlt log-likelihood {result.log_likelihood:.10f} differs from "
            f"R reference {ll_r:.10f} beyond tolerance"
        ),
    )


def test_auglag_converged(reference: dict) -> None:
    """The auglag solver must report convergence on the reference fixture."""
    from pymlt.basis import BernsteinBasis
    from pymlt.optimizer import OptimizerConfig, optimize

    y = np.array(reference["y"], dtype=np.float64)
    support = tuple(float(v) for v in reference["support"])

    basis = BernsteinBasis(order=reference["order"], support=support)
    config = OptimizerConfig(solver="auglag")
    result = optimize(basis, y, config=config)

    assert result.converged, (
        f"auglag did not converge on reference fixture; "
        f"kkt_residual={result.kkt_residual:.3e}, message={result.solver_message!r}"
    )


def test_auglag_monotonicity_satisfied(reference: dict) -> None:
    """Bernstein coefficients must be non-decreasing at the auglag optimum."""
    from pymlt.basis import BernsteinBasis
    from pymlt.optimizer import OptimizerConfig, optimize

    y = np.array(reference["y"], dtype=np.float64)
    support = tuple(float(v) for v in reference["support"])
    order = int(reference["order"])

    basis = BernsteinBasis(order=order, support=support)
    config = OptimizerConfig(solver="auglag")
    result = optimize(basis, y, config=config)

    theta_b = result.theta[: order + 1]
    assert np.all(np.diff(theta_b) >= -1e-6), (
        f"Monotonicity violated at auglag optimum: theta_b={theta_b}"
    )


def test_reference_starting_point(reference: dict) -> None:
    """Sanity check: stored starting point matches pymlt's _initial_theta."""
    from pymlt.optimizer import _initial_theta

    order = int(reference["order"])
    stored_start = np.array(reference["starting_point"], dtype=np.float64)
    expected_start = _initial_theta(order + 1, None)
    np.testing.assert_allclose(stored_start, expected_start, atol=1e-15)


# ---------------------------------------------------------------------------
# Bounded Bernstein fixture — exercises the boundary-equality plumbing
# (build_constraint_matrices: lower/upper → C_eq, d_eq).  Generated by the
# same R script as the Lm fixture above using a tighter inner-solver setting
# so alabama::auglag converges to within rtol=1e-6 of pymlt's auglag.
# ---------------------------------------------------------------------------


_REF_PATH_BOUNDED = (
    Path(__file__).resolve().parent
    / "reference_data"
    / "auglag"
    / "bernstein_bounded_n50_seed42.json"
)


@pytest.fixture(scope="module")
def bounded_reference() -> dict:
    """Load the bounded-Bernstein alabama::auglag reference JSON."""
    if not _REF_PATH_BOUNDED.is_file():
        pytest.skip(f"Reference file not found: {_REF_PATH_BOUNDED}")
    with _REF_PATH_BOUNDED.open() as fh:
        return json.load(fh)


def _bounded_config(reference: dict) -> tuple:
    """Decode the bounded fixture's optional bounds into pymlt arguments."""
    from pymlt.optimizer import OptimizerConfig

    lower = reference.get("lower")
    upper = reference.get("upper")
    # R writes JSON NA as null/None → leave as None for pymlt.
    if lower is not None and not np.isfinite(lower):
        lower = None
    if upper is not None and not np.isfinite(upper):
        upper = None
    return OptimizerConfig(solver="auglag", lower=lower, upper=upper)


def test_auglag_bounded_theta_matches_r(bounded_reference: dict) -> None:
    """pymlt auglag theta must match alabama::auglag with boundary equality."""
    from pymlt.basis import BernsteinBasis
    from pymlt.optimizer import optimize

    y = np.array(bounded_reference["y"], dtype=np.float64)
    support = tuple(float(v) for v in bounded_reference["support"])
    theta_r = np.array(bounded_reference["theta"], dtype=np.float64)

    basis = BernsteinBasis(order=bounded_reference["order"], support=support)
    config = _bounded_config(bounded_reference)
    result = optimize(basis, y, config=config)

    np.testing.assert_allclose(
        result.theta,
        theta_r,
        rtol=1e-6,
        atol=1e-10,
        err_msg=(
            f"pymlt theta {result.theta} differs from R reference {theta_r} "
            f"beyond tolerance (boundary fixture)"
        ),
    )


def test_auglag_bounded_loglik_matches_r(bounded_reference: dict) -> None:
    """pymlt auglag log-likelihood must match alabama::auglag with boundary."""
    from pymlt.basis import BernsteinBasis
    from pymlt.optimizer import optimize

    y = np.array(bounded_reference["y"], dtype=np.float64)
    support = tuple(float(v) for v in bounded_reference["support"])
    ll_r = float(bounded_reference["log_likelihood"])

    basis = BernsteinBasis(order=bounded_reference["order"], support=support)
    config = _bounded_config(bounded_reference)
    result = optimize(basis, y, config=config)

    np.testing.assert_allclose(
        result.log_likelihood,
        ll_r,
        rtol=1e-6,
        atol=1e-10,
        err_msg=(
            f"pymlt log-likelihood {result.log_likelihood:.10f} differs from "
            f"R reference {ll_r:.10f} beyond tolerance (boundary fixture)"
        ),
    )


def test_auglag_bounded_boundary_satisfied(bounded_reference: dict) -> None:
    """Pinned theta entries must equal the requested boundary values."""
    from pymlt.basis import BernsteinBasis
    from pymlt.optimizer import optimize

    y = np.array(bounded_reference["y"], dtype=np.float64)
    support = tuple(float(v) for v in bounded_reference["support"])

    basis = BernsteinBasis(order=bounded_reference["order"], support=support)
    config = _bounded_config(bounded_reference)
    result = optimize(basis, y, config=config)

    p = bounded_reference["order"] + 1
    if config.lower is not None:
        np.testing.assert_allclose(result.theta[0], config.lower, atol=1e-8)
    if config.upper is not None:
        np.testing.assert_allclose(result.theta[p - 1], config.upper, atol=1e-8)


# ---------------------------------------------------------------------------
# Exponential fixture — exercises the per-observation support-inequality
# plumbing in build_constraint_matrices added in slice 3.
# ---------------------------------------------------------------------------


_REF_PATH_EXP = (
    Path(__file__).resolve().parent
    / "reference_data"
    / "auglag"
    / "exponential_n50_seed43.json"
)


@pytest.fixture(scope="module")
def exponential_reference() -> dict:
    """Load the exponential alabama::auglag reference JSON."""
    if not _REF_PATH_EXP.is_file():
        pytest.skip(f"Reference file not found: {_REF_PATH_EXP}")
    with _REF_PATH_EXP.open() as fh:
        return json.load(fh)


def _exp_inputs(reference: dict) -> tuple:
    """Decode arrays from the exponential fixture."""
    y = np.array(reference["y"], dtype=np.float64)
    X = np.array(reference["X"], dtype=np.float64)
    support = tuple(float(v) for v in reference["support"])
    return y, X, support


def test_auglag_exponential_theta_matches_r(exponential_reference: dict) -> None:
    """pymlt auglag theta must match alabama::auglag for exponential + covariates."""
    from pymlt.basis import BernsteinBasis
    from pymlt.optimizer import OptimizerConfig, optimize

    y, X, support = _exp_inputs(exponential_reference)
    theta_r = np.array(exponential_reference["theta"], dtype=np.float64)

    basis = BernsteinBasis(order=exponential_reference["order"], support=support)
    config = OptimizerConfig(solver="auglag")
    result = optimize(basis, y, X=X, config=config, base_distribution="exponential")

    np.testing.assert_allclose(
        result.theta,
        theta_r,
        rtol=1e-6,
        atol=1e-10,
        err_msg=(
            f"pymlt theta {result.theta} differs from R reference {theta_r} "
            f"beyond tolerance (exponential fixture)"
        ),
    )


def test_auglag_exponential_loglik_matches_r(exponential_reference: dict) -> None:
    """pymlt auglag log-likelihood must match alabama::auglag for exponential."""
    from pymlt.basis import BernsteinBasis
    from pymlt.optimizer import OptimizerConfig, optimize

    y, X, support = _exp_inputs(exponential_reference)
    ll_r = float(exponential_reference["log_likelihood"])

    basis = BernsteinBasis(order=exponential_reference["order"], support=support)
    config = OptimizerConfig(solver="auglag")
    result = optimize(basis, y, X=X, config=config, base_distribution="exponential")

    np.testing.assert_allclose(
        result.log_likelihood,
        ll_r,
        rtol=1e-6,
        atol=1e-10,
        err_msg=(
            f"pymlt log-likelihood {result.log_likelihood:.10f} differs from "
            f"R reference {ll_r:.10f} beyond tolerance (exponential fixture)"
        ),
    )


def test_auglag_exponential_support_satisfied(exponential_reference: dict) -> None:
    """theta_b[0] + X_i @ beta must be >= 0 for every training observation."""
    from pymlt.basis import BernsteinBasis
    from pymlt.optimizer import OptimizerConfig, optimize

    y, X, support = _exp_inputs(exponential_reference)
    order = int(exponential_reference["order"])

    basis = BernsteinBasis(order=order, support=support)
    config = OptimizerConfig(solver="auglag")
    result = optimize(basis, y, X=X, config=config, base_distribution="exponential")

    p = order + 1
    theta_b = result.theta[:p]
    beta = result.theta[p:]
    # h(y_min | x_i) = theta_b[0] + X_i @ beta — the binding row of the
    # per-observation support inequality.  Equality at the optimum is allowed.
    h_min = theta_b[0] + X @ beta
    assert np.all(h_min >= -1e-6), (
        f"Support inequality violated at auglag optimum: min h_min = {h_min.min():.3e}"
    )
